server:
  port: 9090
#服务的名称
spring:
  application:
    name: api-gateway
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#自定义路由映射
#/order-service/api/v1/product_order/save?user_id=2&product_id=1
zuul:
  routes:
    order-service: /apigateway/order/**
    product-service: /apigateway/product/**
  #统一入口为上面的路由,不能通过服务名访问
  ignored-patterns: /*-service/**
  #处理http请求头为空的问题
  sensitiveHeaders:
