#端口号
server:
  port: 9100
#声明服务名称
spring:
  application:
    name: config-server
  #git配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/frank1245/config-server
          username: frank1245
          password: Lg19960129
          #超时时间
          timeout: 5
          #分支
          default-label: master

#Eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/